<%@ Page Title="" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="EmpManagement.aspx.cs" Inherits="LMS.Admin.WebForm2" %>

<%@ Register Assembly="AjaxControlToolkit" Namespace="AjaxControlToolkit" TagPrefix="ajaxToolkit" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
     <style type="text/css">  
        .Background  
        {  
            background-color: Black;  
            filter: alpha(opacity=90);  
            opacity: 0.8;  
        }  
        .Popup  
        {  
            background-color: #FFFFFF;  
            border-width: 3px;  
            border-style: solid;  
            border-color: black;  
            padding-top: 10px;  
            padding-left: 10px;  
            width: 400px;  
            height: 600px;  
        }  
        .lbl  
        {  
            font-size:16px;  
            font-style:italic;  
            font-weight:bold;  
        }  
    </style>  
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    <asp:GridView ID="GridView1" runat="server" AllowPaging="True" AllowSorting="True" AutoGenerateColumns="False" DataKeyNames="empID" DataSourceID="SqlDataSource1" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BorderColor="Black" Width="1255px">
        <Columns>
            <asp:BoundField DataField="empID" HeaderText="empID" ReadOnly="True" SortExpression="empID" Visible="False" />
            <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
            <asp:BoundField DataField="Gender" HeaderText="Gender" SortExpression="Gender" />
            <asp:BoundField DataField="JoiningDate" HeaderText="Joining Date" SortExpression="JoiningDate" ApplyFormatInEditMode="true" DataFormatString="{0:d}" />
            <asp:BoundField DataField="MobileNo" HeaderText="Mobile No" SortExpression="MobileNo" />
            <asp:BoundField DataField="Email" HeaderText="Email" SortExpression="Email" />
            <asp:BoundField DataField="Address" HeaderText="Address" SortExpression="Address" />
            <asp:BoundField DataField="DateOfBirth" HeaderText="Date Of Birth" SortExpression="DateOfBirth" ApplyFormatInEditMode="true" DataFormatString="{0:d}" />
            <asp:BoundField DataField="TotalLeaves" HeaderText="Total Allotted Leaves" SortExpression="TotalLeaves" />
        </Columns>
        <EditRowStyle ForeColor="White" />
        <HeaderStyle BackColor="#FF9900" />
    </asp:GridView>
    <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConflictDetection="CompareAllValues" ConnectionString="<%$ ConnectionStrings:LMSConnectionString %>" DeleteCommand="DELETE FROM [empDetails] WHERE [empID] = @original_empID AND [Name] = @original_Name AND [Gender] = @original_Gender AND [JoiningDate] = @original_JoiningDate AND [Email] = @original_Email AND [Address] = @original_Address AND [DateOfBirth] = @original_DateOfBirth AND [TotalLeaves] = @original_TotalLeaves AND [MobileNo] = @original_MobileNo" InsertCommand="INSERT INTO [empDetails] ([empID], [Name], [Gender], [JoiningDate], [Email], [Address], [DateOfBirth], [TotalLeaves], [MobileNo]) VALUES (@empID, @Name, @Gender, @JoiningDate, @Email, @Address, @DateOfBirth, @TotalLeaves, @MobileNo)"  SelectCommand="SELECT [empID], [Name], CASE WHEN [Gender]=0 THEN 'Male'
WHEN [Gender]=1 THEN 'Female' END AS [Gender]
, [JoiningDate], [Email], [Address], [DateOfBirth], [TotalLeaves], [MobileNo] FROM [empDetails] ORDER BY [JoiningDate]" UpdateCommand="UPDATE [empDetails] SET [Name] = @Name, [Gender] = @Gender, [JoiningDate] = @JoiningDate, [Email] = @Email, [Address] = @Address, [DateOfBirth] = @DateOfBirth, [TotalLeaves] = @TotalLeaves, [MobileNo] = @MobileNo WHERE [empID] = @original_empID" OldValuesParameterFormatString="original_{0}">
        <DeleteParameters>
            <asp:Parameter Name="original_empID" Type="Object" />
            <asp:Parameter Name="original_Name" Type="String" />
            <asp:Parameter Name="original_Gender" Type="String" />
            <asp:Parameter Name="original_JoiningDate" Type="DateTime" />
            <asp:Parameter Name="original_Email" Type="String" />
            <asp:Parameter Name="original_Address" Type="String" />
            <asp:Parameter Name="original_DateOfBirth" Type="DateTime" />
            <asp:Parameter Name="original_TotalLeaves" Type="Byte" />
            <asp:Parameter Name="original_MobileNo" Type="String" />
        </DeleteParameters>
        <InsertParameters>
            <asp:Parameter Name="empID" />
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Gender" Type="String" />
            <asp:Parameter Name="JoiningDate" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="DateOfBirth" />
            <asp:Parameter Name="TotalLeaves" />
            <asp:Parameter Name="MobileNo" />
        </InsertParameters>
        <UpdateParameters>
            <asp:Parameter Name="Name" Type="String" />
            <asp:Parameter Name="Gender" Type="String" />
            <asp:Parameter Name="JoiningDate" />
            <asp:Parameter Name="Email" Type="String" />
            <asp:Parameter Name="Address" Type="String" />
            <asp:Parameter Name="DateOfBirth" />
            <asp:Parameter Name="TotalLeaves" />
            <asp:Parameter Name="MobileNo" />
            <asp:Parameter Name="original_empID" Type="Object" />
        </UpdateParameters>
    </asp:SqlDataSource>
    <asp:Label ID="Label13" runat="server" Text="Record saved successfully" ></asp:Label>


    <asp:Button ID="Button1" runat="server" Text="Add Employee" />
    <asp:ScriptManager ID="ScriptManager1" runat="server"></asp:ScriptManager>
    <asp:Panel ID="Panel1" runat="server" CssClass="Popup" align="center" style = "display:none">
        <iframe style=" width: 350px; height: 550px;" id="irm1" src="AddEmployeeForm.aspx" runat="server"></iframe>  
   <br/> 
        <asp:Button ID="Button4" runat="server" Text="Close" OnClick="Button4_Click" />
        </asp:Panel>
    <ajaxToolkit:ModalPopupExtender ID="ModalPopupExtender1" runat="server" TargetControlID="Button1" CancelControlID="Button4" OnUnload="Page_Load" PopupControlID="Panel1" BackgroundCssClass="Background"></ajaxToolkit:ModalPopupExtender>


    
</asp:Content>
    
