<%@ Page Title="LeaveTypes" Language="C#" MasterPageFile="~/Admin/Admin.Master" AutoEventWireup="true" CodeBehind="leave_category.aspx.cs" Inherits="LMS.Admin.WebForm3" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
    
    

    <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="CategoryID" DataSourceID="SqlDataSource1">
    <Columns>
        <asp:BoundField DataField="CategoryID" HeaderText="CategoryID" ReadOnly="True" SortExpression="CategoryID" />
        <asp:BoundField DataField="Leave_Category" HeaderText="Leave_Category" SortExpression="Leave_Category" />
        <asp:BoundField DataField="ShortName" HeaderText="ShortName" SortExpression="ShortName" />
    </Columns>
</asp:GridView>
<asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:LMSConnectionString %>" SelectCommand="Select * from [leave_Category]" UpdateCommand="Update [leave_category] set [CategoryID]=@CategoryID,[Leave_Category]=@Leave_Category,[ShortName]=@ShortName"   DeleteCommand="Delete from [leave_Category] where [CategoryID]=@CategoryID"></asp:SqlDataSource>
    
    

    <table>
        <tr>
            <td>
                <asp:Label ID="Label1" runat="server" Text="CategoryID"></asp:Label>&nbsp;&nbsp;
                </td>
            <td>
                <asp:TextBox ID="TextBox1" runat="server" TextMode="Number" AutoCompleteType="Disabled"></asp:TextBox>


            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="Label2" runat="server" Text="Leave Category"></asp:Label>&nbsp;&nbsp;
                </td>
            <td>
                <asp:TextBox ID="TextBox2" runat="server" AutoCompleteType="Disabled"></asp:TextBox>


            </td>
        </tr>
        <tr>
            <td>
                <asp:Label ID="Label3" runat="server" Text="Short Name: " ></asp:Label>&nbsp;&nbsp;
                </td>
            <td>
                <asp:TextBox ID="TextBox3" runat="server" MaxLength="2" AutoCompleteType="Disabled"></asp:TextBox>


            </td>
        </tr>
        <tr>
            <td>
                </td>
            <td>
                <asp:Button ID="Button1" runat="server" Text="Save"  OnClick="Button1_Click"/>


            </td>
        </tr>
    </table>
</asp:Content>
